---
version: '2'

networks:
  backend:
    driver: bridge

volumes:
  koha_state: {}

services:
  koha:
    container_name: xkoha
    image: "digibib/koha:${KOHA_IMAGE_TAG}"
    networks:
      - backend
    depends_on:
      - koha_mysql
      - koha_index
      - sms
      - smtp
      - sip_proxy
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
      - MKNOD
    environment:
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "$KOHA_INSTANCE"
      KOHA_DBHOST: koha_mysql
      DEFAULT_LANGUAGE: nb-NO
      EMAIL_ENABLED: "True"
      SMTP_SERVER_HOST: mailrelay # access through network 'backend'
      SMTP_SERVER_PORT: 2525
      MESSAGE_QUEUE_FREQUENCY: 1
      SMS_SENDER: "${SMS_SENDER}"
      SMS_DRIVER: "${SMS_DRIVER}"
      SMS_USER: "${SMS_USER}"
      SMS_PASS: "${SMS_PASS}"
      API_PASSPHRASE: "${API_PASSPHRASE}"
      NLBASEUSER: "${NLBASEUSER}"
      NLBASEPASS: "${NLBASEPASS}"
      NLVENDORURL: "${NLVENDORURL}"
      NLVENDORUSER: "${NLVENDORUSER}"
      NLVENDORPASS: "${NLVENDORPASS}"
      NLVENDORKEY: "${NLVENDORKEY}"
      PIDGEON_URL: "${PIDGEON_URL}"
      PIDGEON_USER: "${PIDGEON_USER}"
      PIDGEON_PASS: "${PIDGEON_PASS}"
      SIP_AUTOPASS: "${SIP_AUTOPASS}"
      APACHE_MINSERVERS: "${APACHE_MINSERVERS}"
      APACHE_TIMEOUT: "${APACHE_TIMEOUT}"
      APACHE_SERVER_STATUS_NET: "${APACHE_SERVER_STATUS_NET}"
      APACHE_REMOTE_INTERNAL_PROXY: "${APACHE_REMOTE_INTERNAL_PROXY}"
    ports:
      - "6001:6001"
      - "8080:8080"
      - "8081:8081"
    volumes_from:
      - koha_index
    volumes:
      - koha_state:/var/lib/state
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  koha_mysql:
    container_name: koha_mysql
    image: mysql:5.6.20
    networks:
      - backend
    cap_add:
      - MKNOD
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
    environment:
      MYSQL_DATABASE: "koha_${KOHA_INSTANCE}"
      MYSQL_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_ROOT_PASSWORD: "${KOHA_ADMINPASS}"
      MYSQL_USER: "${KOHA_ADMINUSER}"
    ports:
      - "3306:3306"
    volumes_from:
      - koha_mysql_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  koha_mysql_data:
    container_name: koha_mysql_data
    image: "busybox:latest"
    volumes:
      - /var/lib/mysql

  koha_index:
    container_name: koha_index
    image: "busybox:latest"
    volumes:
      - "/var/lib/koha/${KOHA_INSTANCE}"

  rfidhub:
    container_name: rfidhub
    image: "digibib/rfidhub2:5cc223d57472232557fbcc608c45f7ac22372fb9"
    networks:
      - backend
    depends_on:
      - sip_proxy
    ports:
      - "6006:6006"
      - "8899:8899"
    environment:
      SIP_SERVER: sip_proxy:9999
      TCP_PORT: 6006
      SIP_USER: rfidhub
      SIP_PASS: "${SIP_AUTOPASS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  smtp:
    container_name: mailrelay
    image: "digibib/gosmtpd:e51ec0b872867560461ab1e8c12b10fd63f5d3c1"
    networks:
      - backend
    ports:
      - "8100:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  sms:
    container_name: smsproxy
    image: "digibib/proximity:3ce6b65df303302420d2fb85bd6b625744bfb907"
    networks:
      - backend
    ports:
      - "8101:9999"
    environment:
      FORWARD_SMS: https://tcpsink:9999
    command:
      - "/proximity"
      - "-no-verify"
      - "-r"
      - '${FORWARD_SMS}'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  tcpsink: # Fake webserver response, for testing
    container_name: tcpsink
    image: "alpine:3.3"
    networks:
      - backend
    ports:
      - "9999:9999"
    command:
      - "/bin/sh"
      - "-c"
      - "mkfifo pipe; while true ; do { read line<pipe;echo -e 'HTTP/1.1 200 OK\\r\\n' ; } | nc -l -p 9999 > pipe; done"

  nlsink: # Fake NL response, for testing
    container_name: nlsink
    image: "alpine:3.3"
    networks:
      - backend
    ports:
      - "9998:9999"
    command:
      - "/bin/sh"
      - "-c"
      - "mkfifo pipe; while true ; do { read line<pipe;echo -e 'HTTP/1.1 200 OK\nContent-Type: text/xml; charset=utf-8\n\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ns0:Envelope xmlns:ns0=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:ns1=\"http://lanekortet.no\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" ns0:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n<ns0:Body>\n<ns1:hentResponse>\n<return xsi:type=\"ns1:Resultat\">\n<status xsi:type=\"xsd:boolean\">true</status>\n<melding xsi:type=\"xsd:string\">OK</melding>\n<antall_treff xsi:type=\"xsd:int\">0</antall_treff>\n<antall_poster_returnert xsi:type=\"xsd:int\">0</antall_poster_returnert>\n<neste_indeks xsi:type=\"xsd:int\">0</neste_indeks>\n<server_tid xsi:type=\"xsd:string\">2016-07-07T11:29:08</server_tid>\n</return>\n</ns1:hentResponse>\n</ns0:Body>\n</ns0:Envelope>\n' ; } | nc -l -p 9999 > pipe; done"

  elasticsearch_data:
    container_name: elasticsearch_data
    image: "busybox:latest"
    volumes:
      - /usr/share/elasticsearch/data

  elasticsearch:
    container_name: elasticsearch
    image: digibib/elasticsearch:6bf766734e7f82a6f0d4a406ca9a528a67c02801
    networks:
      - backend
    ports:
      - "9200:9200"
    volumes_from:
      - elasticsearch_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  fuseki_data:
    container_name: fuseki_data
    image: "busybox:latest"
    volumes:
      - /data/databases/ds

  fuseki:
    container_name: fuseki
    image: "digibib/fuseki2"
    networks:
      - backend
    ports:
      - "3030:3030"
    volumes_from:
      - fuseki_data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  sip_proxy:
    container_name: sip_proxy
    image: "digibib/sip2proxy:a387e6d35e38c488b0f4ec7bc0c7292e19dd61df"
    networks:
      - backend
    ports:
      - "6002:9999"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT}"
      - "-log-messages=true"
      - "-replace-10=true"
      - "-log-metrics-every-s=300"
      - "-ensure-branch=true"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  catalinker:
    container_name: catalinker
    build:
      context: "${LSEXTPATH}/redef/catalinker"
      dockerfile: Dockerfile-dev
    networks:
      - backend
    depends_on:
      - services
      - z3950proxy
    volumes:
      - ${MOUNTPATH}/redef/catalinker/client:/usr/src/app/client
      - ${MOUNTPATH}/redef/catalinker/public:/usr/src/app/public
      - ${MOUNTPATH}/redef/catalinker/server:/usr/src/app/server
    ports:
      - "8010:8010"
    environment:
      KOHA_OPAC_PORT: "http://xkoha:8080"
      KOHA_INTRA_PORT: "http://xkoha:8081"
      SERVICES_PORT: "http://services:8005"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  build_services:
    container_name: build_services
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile.build
    volumes:
      - "${LSEXTPATH}/redef/services/build:/services/build"

  services:
    container_name: services
    build:
      context: "${LSEXTPATH}/redef/services"
      dockerfile: Dockerfile.dev
    networks:
      - backend
    depends_on:
      - build_services
      - fuseki
      - koha
    ports:
      - "8005:8005"
      - "8006:8006"
      - "5070:5070"
    environment:
      KOHA_MYSQL_USER: "${KOHA_ADMINUSER}"
      KOHA_MYSQL_PASS: "${KOHA_ADMINPASS}"
      KOHA_MYSQL_DB: "koha_${KOHA_INSTANCE}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
      KOHA_API_PASS_ENCRYPTED: "${KOHA_API_PASS_ENCRYPTED_ESCAPED}" # For mysql regeneration
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  patron_client:
    container_name: patron_client
    networks:
      - backend
    depends_on:
      - services
    build:
      context: "${LSEXTPATH}/redef/patron-client"
      dockerfile: Dockerfile-dev
    volumes:
      - ${MOUNTPATH}/redef/patron-client/src:/usr/src/app/src
      - ${MOUNTPATH}/redef/patron-client/test:/usr/src/app/test
    ports:
      - "8000:8000"
      - "35729:35729"
    environment:
      SERVICES_PORT: "http://services:${SERVICES_PORT}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  overview:
    container_name: overview
    build:
      context: "${LSEXTPATH}/redef/overview"
    networks:
      - backend
    ports:
      - "${OVERVIEW_PORT}:${OVERVIEW_PORT}"
    environment:
      HOST: "${HOST}"
      PATRON_CLIENT_PORT: "8000"
      SERVICES_PORT: "8005"
      CATALINKER_PORT: "8010"
      KOHA_OPAC_PORT: "8080"
      KOHA_INTRA_PORT: "8081"
      JAMON_PORT: "5070"
      TRIPLESTORE_PORT: "${TRIPLESTORE_PORT}"
      ELASTICSEARCH_PORT: "${ELASTICSEARCH_PORT}"
      KOHA_VERSION: "${KOHA_IMAGE_TAG}"
      GITREF: "${GITREF}"
      BUILD_TAG: "${BUILD_TAG}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  cuke_tests:
    container_name: cuke_tests
    build:
      context: "${LSEXTPATH}/test"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${LSEXTPATH}/test:/tests"
    environment:
      HOST: "${HOST}"
      KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
      KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
      KOHA_INSTANCE: "${KOHA_INSTANCE}"
      KOHA_API_USER: "${KOHA_API_USER}"
      KOHA_API_PASS: "${KOHA_API_PASS}"

  z3950proxy:
    container_name: z3950proxy
    image: "digibib/z3950proxy:331137ac40ba155760c311e5197fa9fa73cf4c27"
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      APPSECRET: "${Z3950SECRET}"
      BS_SERVER: "${BS_SERVER}"
      BS_PORT: "${BS_PORT}"
      BS_DB: "${BS_DB}"
      BS_USER: "${BS_USER}"
      BS_PASS: "${BS_PASS}"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  migration:
    container_name: migration
    build:
      context: "${LSEXTPATH}/docker-compose/dockerfiles/migration"
      args:
        - MYSQL_DATABASE=koha_${KOHA_INSTANCE}
        - MYSQL_USER=${KOHA_ADMINUSER}
        - MYSQL_PASSWORD=${KOHA_ADMINPASS}
    networks:
      - backend
